# Applied Data Science Capstone Project

###Description of the problem

The project will look at popular venues in Cape Town, South Africa. 
The project is concerning neighborhoods in Cape Town, South Africa, and the similarities between suburbs. 
The project will identify the most popular venues per suburb based on the geographical location of the suburb. 

###Background of the problem

The project will aim to cluster neighborhoods together. the clustering will not be based on the distances of neigborhoods to a central point per cluster, but will rather cluster neighborhoods together in relation to which venues are the most popular per neighborhood and then which neighborhoods are most similar to each other in relation to these popular venues. in essence the project will aim to cluster neighborhoods together that are the most similar with regards to the venues that are in those neighborhoods.

###Data
Step 1 - I scraped data for Cape Town suburbs from the internet
Step 2 - I made a Pandas dataframe from the data
Step 3 - I cleaned the data to be left with a column for suburbs and a column for postal codes
Step 4 - I dropped all the rows with NaN values
Step 5 - I changed the postal code values from float values to integers
Step 6 - I imported a csv file that contains the coordinates for the Cape Town Suburbs
Step 7 - I merged the two tables to form a final data table
Step 8 - I cleaned this table to be left with a table with suburb names, postal codes, longitude coordinates and latitude coordinates

In [25]:
import pandas as pd
import numpy as np

In [26]:
url = 'http://geo.mycyberict.com/south_africa/cape-town/'

In [27]:
df = pd.read_html(url, header=0)
df

[            State: Western Cape
 0  No. of Suburbs:  178 suburbs,
                               Suburb  Zip Code  Postal Code
 0                                NaN    8000.0       8001.0
 1                            Athlone    7760.0       7764.0
 2                Athlone Industria 1       NaN       7764.0
 3                Athlone Industria 2       NaN       7764.0
 4                            Bakoven       NaN       8005.0
 5                         Bantry BAY       NaN       8005.0
 6                         Bantrybaai       NaN       8005.0
 7                             Belhar    7507.0       7493.0
 8                          Bellville    7535.0       7530.0
 9                          Bergvliet    7864.0       7945.0
 10                           BO-Kaap    8001.0       8001.0
 11                          Bothasig    7406.0       7441.0
 12                       Brackenfell    7561.0       7560.0
 13                         Camps BAY    8040.0       8005.0
 14   Cape Town International Airport    7525.0          NaN
 15                          Capemail    8003.0          NaN
 16                           Central       NaN       8001.0
 17                         Claremont    7735.0       7708.0
 18                           Clifton       NaN       8005.0
 19                  Competition Mail    8017.0          NaN
 20                        Constantia    7848.0       7806.0
 21                      DE Waterkant       NaN       8001.0
 22                  Devil'S Peak EST       NaN       8001.0
 23                        Diep River       NaN       7800.0
 24                       Diep Rivier       NaN       7800.0
 25                     Drieankerbaai       NaN       8005.0
 26                  Duiwelskloof LGD       NaN       8001.0
 27                       Durbanville    7551.0       7550.0
 28                          Edgemead    7407.0       7441.0
 29                      Eerste River    7103.0       7100.0
 ..                               ...       ...          ...
 148                        Roggebaai    8012.0          NaN
 149                      Rontree EST       NaN       8005.0
 150                      Rontree LGD       NaN       8005.0
 151                       Salt River       NaN       7925.0
 152                  Schotsche Kloof       NaN       8001.0
 153                        SEA Point    8060.0       8005.0
 154                          Seepunt    8060.0       8005.0
 155                       Seinheuwel       NaN       8001.0
 156                         Sentraal       NaN       8001.0
 157                      Signal Hill       NaN       8001.0
 158                   SIR Lowry Road       NaN       7925.0
 159                       Southfield    7880.0       7800.0
 160                       Soutrivier       NaN       7925.0
 161                Table BAY Harbour       NaN       8001.0
 162                       Table View    7439.0       7441.0
 163                    Tafelbaaihawe       NaN       8001.0
 164                    Tamboerskloof       NaN       8001.0
 165                 Three Anchor BAY       NaN       8005.0
 166                            Tokai    7966.0       7945.0
 167                Victoria Junction    8001.0       8001.0
 168                          Vishoek    7974.0       7975.0
 169                         Vlaeberg    8018.0          NaN
 170                        Vredehoek       NaN       8001.0
 171                  Vredendal North    8161.0       8160.0
 172                  Vredendal-Noord    8161.0       8160.0
 173                       Waterfront    8002.0       8001.0
 174                         Westlake       NaN       7945.0
 175                        Woodstock    7915.0       7925.0
 176                          Wynberg    7824.0       7800.0
 177                       Ysterplaat    7425.0       7405.0

 [178 rows x 3 columns]]

In [28]:
df1 = df[1]

In [29]:
df1

                              Suburb  Zip Code  Postal Code
0                                NaN    8000.0       8001.0
1                            Athlone    7760.0       7764.0
2                Athlone Industria 1       NaN       7764.0
3                Athlone Industria 2       NaN       7764.0
4                            Bakoven       NaN       8005.0
5                         Bantry BAY       NaN       8005.0
6                         Bantrybaai       NaN       8005.0
7                             Belhar    7507.0       7493.0
8                          Bellville    7535.0       7530.0
9                          Bergvliet    7864.0       7945.0
10                           BO-Kaap    8001.0       8001.0
11                          Bothasig    7406.0       7441.0
12                       Brackenfell    7561.0       7560.0
13                         Camps BAY    8040.0       8005.0
14   Cape Town International Airport    7525.0          NaN
15                          Capemail    8003.0          NaN
16                           Central       NaN       8001.0
17                         Claremont    7735.0       7708.0
18                           Clifton       NaN       8005.0
19                  Competition Mail    8017.0          NaN
20                        Constantia    7848.0       7806.0
21                      DE Waterkant       NaN       8001.0
22                  Devil'S Peak EST       NaN       8001.0
23                        Diep River       NaN       7800.0
24                       Diep Rivier       NaN       7800.0
25                     Drieankerbaai       NaN       8005.0
26                  Duiwelskloof LGD       NaN       8001.0
27                       Durbanville    7551.0       7550.0
28                          Edgemead    7407.0       7441.0
29                      Eerste River    7103.0       7100.0
..                               ...       ...          ...
148                        Roggebaai    8012.0          NaN
149                      Rontree EST       NaN       8005.0
150                      Rontree LGD       NaN       8005.0
151                       Salt River       NaN       7925.0
152                  Schotsche Kloof       NaN       8001.0
153                        SEA Point    8060.0       8005.0
154                          Seepunt    8060.0       8005.0
155                       Seinheuwel       NaN       8001.0
156                         Sentraal       NaN       8001.0
157                      Signal Hill       NaN       8001.0
158                   SIR Lowry Road       NaN       7925.0
159                       Southfield    7880.0       7800.0
160                       Soutrivier       NaN       7925.0
161                Table BAY Harbour       NaN       8001.0
162                       Table View    7439.0       7441.0
163                    Tafelbaaihawe       NaN       8001.0
164                    Tamboerskloof       NaN       8001.0
165                 Three Anchor BAY       NaN       8005.0
166                            Tokai    7966.0       7945.0
167                Victoria Junction    8001.0       8001.0
168                          Vishoek    7974.0       7975.0
169                         Vlaeberg    8018.0          NaN
170                        Vredehoek       NaN       8001.0
171                  Vredendal North    8161.0       8160.0
172                  Vredendal-Noord    8161.0       8160.0
173                       Waterfront    8002.0       8001.0
174                         Westlake       NaN       7945.0
175                        Woodstock    7915.0       7925.0
176                          Wynberg    7824.0       7800.0
177                       Ysterplaat    7425.0       7405.0

[178 rows x 3 columns]

In [30]:
df1=df1.drop(['Zip Code'],axis=1)
df1

                              Suburb  Postal Code
0                                NaN       8001.0
1                            Athlone       7764.0
2                Athlone Industria 1       7764.0
3                Athlone Industria 2       7764.0
4                            Bakoven       8005.0
5                         Bantry BAY       8005.0
6                         Bantrybaai       8005.0
7                             Belhar       7493.0
8                          Bellville       7530.0
9                          Bergvliet       7945.0
10                           BO-Kaap       8001.0
11                          Bothasig       7441.0
12                       Brackenfell       7560.0
13                         Camps BAY       8005.0
14   Cape Town International Airport          NaN
15                          Capemail          NaN
16                           Central       8001.0
17                         Claremont       7708.0
18                           Clifton       8005.0
19                  Competition Mail          NaN
20                        Constantia       7806.0
21                      DE Waterkant       8001.0
22                  Devil'S Peak EST       8001.0
23                        Diep River       7800.0
24                       Diep Rivier       7800.0
25                     Drieankerbaai       8005.0
26                  Duiwelskloof LGD       8001.0
27                       Durbanville       7550.0
28                          Edgemead       7441.0
29                      Eerste River       7100.0
..                               ...          ...
148                        Roggebaai          NaN
149                      Rontree EST       8005.0
150                      Rontree LGD       8005.0
151                       Salt River       7925.0
152                  Schotsche Kloof       8001.0
153                        SEA Point       8005.0
154                          Seepunt       8005.0
155                       Seinheuwel       8001.0
156                         Sentraal       8001.0
157                      Signal Hill       8001.0
158                   SIR Lowry Road       7925.0
159                       Southfield       7800.0
160                       Soutrivier       7925.0
161                Table BAY Harbour       8001.0
162                       Table View       7441.0
163                    Tafelbaaihawe       8001.0
164                    Tamboerskloof       8001.0
165                 Three Anchor BAY       8005.0
166                            Tokai       7945.0
167                Victoria Junction       8001.0
168                          Vishoek       7975.0
169                         Vlaeberg          NaN
170                        Vredehoek       8001.0
171                  Vredendal North       8160.0
172                  Vredendal-Noord       8160.0
173                       Waterfront       8001.0
174                         Westlake       7945.0
175                        Woodstock       7925.0
176                          Wynberg       7800.0
177                       Ysterplaat       7405.0

[178 rows x 2 columns]

In [31]:
#Remove Not assigned boroughs
df1=df1.dropna()
print(df1)

                  Suburb  Postal Code
1                Athlone       7764.0
2    Athlone Industria 1       7764.0
3    Athlone Industria 2       7764.0
4                Bakoven       8005.0
5             Bantry BAY       8005.0
6             Bantrybaai       8005.0
7                 Belhar       7493.0
8              Bellville       7530.0
9              Bergvliet       7945.0
10               BO-Kaap       8001.0
11              Bothasig       7441.0
12           Brackenfell       7560.0
13             Camps BAY       8005.0
16               Central       8001.0
17             Claremont       7708.0
18               Clifton       8005.0
20            Constantia       7806.0
21          DE Waterkant       8001.0
22      Devil'S Peak EST       8001.0
23            Diep River       7800.0
24           Diep Rivier       7800.0
25         Drieankerbaai       8005.0
26      Duiwelskloof LGD       8001.0
27           Durbanville       7550.0
28              Edgemead       7441.0
29          Eerste River       7100.0
30          Eersterivier       7100.0
31             Fish Hoek       7975.0
32             Foreshore       8001.0
33              Fresnaye       8005.0
..                   ...          ...
141            Plumstead       7800.0
142              Retreat       7945.0
149          Rontree EST       8005.0
150          Rontree LGD       8005.0
151           Salt River       7925.0
152      Schotsche Kloof       8001.0
153            SEA Point       8005.0
154              Seepunt       8005.0
155           Seinheuwel       8001.0
156             Sentraal       8001.0
157          Signal Hill       8001.0
158       SIR Lowry Road       7925.0
159           Southfield       7800.0
160           Soutrivier       7925.0
161    Table BAY Harbour       8001.0
162           Table View       7441.0
163        Tafelbaaihawe       8001.0
164        Tamboerskloof       8001.0
165     Three Anchor BAY       8005.0
166                Tokai       7945.0
167    Victoria Junction       8001.0
168              Vishoek       7975.0
170            Vredehoek       8001.0
171      Vredendal North       8160.0
172      Vredendal-Noord       8160.0
173           Waterfront       8001.0
174             Westlake       7945.0
175            Woodstock       7925.0
176              Wynberg       7800.0
177           Ysterplaat       7405.0

[161 rows x 2 columns]

In [32]:
#get rid of the decimal after the postal codes
df1.dtypes

Suburb          object
Postal Code    float64
dtype: object

In [33]:
df1=df1.astype({"Postal Code":int})
df1

                  Suburb  Postal Code
1                Athlone         7764
2    Athlone Industria 1         7764
3    Athlone Industria 2         7764
4                Bakoven         8005
5             Bantry BAY         8005
6             Bantrybaai         8005
7                 Belhar         7493
8              Bellville         7530
9              Bergvliet         7945
10               BO-Kaap         8001
11              Bothasig         7441
12           Brackenfell         7560
13             Camps BAY         8005
16               Central         8001
17             Claremont         7708
18               Clifton         8005
20            Constantia         7806
21          DE Waterkant         8001
22      Devil'S Peak EST         8001
23            Diep River         7800
24           Diep Rivier         7800
25         Drieankerbaai         8005
26      Duiwelskloof LGD         8001
27           Durbanville         7550
28              Edgemead         7441
29          Eerste River         7100
30          Eersterivier         7100
31             Fish Hoek         7975
32             Foreshore         8001
33              Fresnaye         8005
..                   ...          ...
141            Plumstead         7800
142              Retreat         7945
149          Rontree EST         8005
150          Rontree LGD         8005
151           Salt River         7925
152      Schotsche Kloof         8001
153            SEA Point         8005
154              Seepunt         8005
155           Seinheuwel         8001
156             Sentraal         8001
157          Signal Hill         8001
158       SIR Lowry Road         7925
159           Southfield         7800
160           Soutrivier         7925
161    Table BAY Harbour         8001
162           Table View         7441
163        Tafelbaaihawe         8001
164        Tamboerskloof         8001
165     Three Anchor BAY         8005
166                Tokai         7945
167    Victoria Junction         8001
168              Vishoek         7975
170            Vredehoek         8001
171      Vredendal North         8160
172      Vredendal-Noord         8160
173           Waterfront         8001
174             Westlake         7945
175            Woodstock         7925
176              Wynberg         7800
177           Ysterplaat         7405

[161 rows x 2 columns]

In [38]:
# The code was removed by Watson Studio for sharing.

   Unnamed: 0  Postal Code  Latidude  Longitude
0           1         7441   33.8660    18.5344
1           2         7945   34.0708    18.4632
2           3         7100   33.9970    18.6948
3           4         7130   34.0947    18.9265
4           5         7530   33.8906    18.6532

In [39]:
#merge the two tables
df_final=pd.merge(df1,df_data_1,on='Postal Code')
df_final

                 Suburb  Postal Code  Unnamed: 0  Latidude  Longitude
0               Athlone         7764          24   33.9673    18.5404
1   Athlone Industria 1         7764          24   33.9673    18.5404
2   Athlone Industria 2         7764          24   33.9673    18.5404
3            Gatesville         7764          24   33.9673    18.5404
4             Bellville         7530           5   33.8906    18.6532
5             Bergvliet         7945           2   34.0708    18.4632
6            Muizenberg         7945           2   34.0708    18.4632
7               Retreat         7945           2   34.0708    18.4632
8                 Tokai         7945           2   34.0708    18.4632
9              Westlake         7945           2   34.0708    18.4632
10              BO-Kaap         8001          11   33.9211    18.4217
11              Central         8001          11   33.9211    18.4217
12         DE Waterkant         8001          11   33.9211    18.4217
13     Devil'S Peak EST         8001          11   33.9211    18.4217
14     Duiwelskloof LGD         8001          11   33.9211    18.4217
15            Foreshore         8001          11   33.9211    18.4217
16              Gardens         8001          11   33.9211    18.4217
17            Higgovale         8001          11   33.9211    18.4217
18            High Cape         8001          11   33.9211    18.4217
19        Highlands EST         8001          11   33.9211    18.4217
20        Highlands LGD         8001          11   33.9211    18.4217
21             Kloofnek         8001          11   33.9211    18.4217
22          Oranjezicht         8001          11   33.9211    18.4217
23      Schotsche Kloof         8001          11   33.9211    18.4217
24           Seinheuwel         8001          11   33.9211    18.4217
25             Sentraal         8001          11   33.9211    18.4217
26          Signal Hill         8001          11   33.9211    18.4217
27    Table BAY Harbour         8001          11   33.9211    18.4217
28        Tafelbaaihawe         8001          11   33.9211    18.4217
29        Tamboerskloof         8001          11   33.9211    18.4217
..                  ...          ...         ...       ...        ...
45           Southfield         7800          45   34.0107    18.4691
46              Wynberg         7800          45   34.0107    18.4691
47          Durbanville         7550          13   33.8475    18.6532
48         Eerste River         7100           3   33.9970    18.6948
49         Eersterivier         7100           3   33.9970    18.6948
50            Fish Hoek         7975          10   34.1418    18.3861
51              Vishoek         7975          10   34.1418    18.3861
52          Grassy Park         7941          19   34.0634    18.5107
53        Groote Schuur         7925          17   33.9353    18.4691
54          Observatory         7925          17   33.9353    18.4691
55           Salt River         7925          17   33.9353    18.4691
56       SIR Lowry Road         7925          17   33.9353    18.4691
57           Soutrivier         7925          17   33.9353    18.4691
58            Woodstock         7925          17   33.9353    18.4691
59         Hanover Park         7780           8   33.9926    18.5166
60            Lansdowne         7780           8   33.9926    18.5166
61          Khayelitsha         7784          18   34.0552    18.7007
62             Maitland         7405          16   33.9209    18.4929
63       Paarden Island         7405          16   33.9209    18.4929
64        Paardeneiland         7405          16   33.9209    18.4929
65            Pinelands         7405          16   33.9209    18.4929
66           Ysterplaat         7405          16   33.9209    18.4929
67       Matroosfontein         7490          47   33.9447    18.5819
68      Mitchells Plain         7785           7   34.0404    18.6235
69      Mitchells Plein         7785           7   34.0404    18.6235
70          Monte Vista         7460           9   33.9117    18.5523
71              Mowbray         7700          34   33.9658    18.4810
72             Newlands         7700          34   33.9658    18.4810
73             Nuweland         7700          34   33.9658    18.4810
74                Parow         7500          27   33.8801    18.5819

[75 rows x 5 columns]

In [42]:
df_final=df_final.drop(['Unnamed: 0'],axis=1)
df_final

                 Suburb  Postal Code  Latidude  Longitude
0               Athlone         7764   33.9673    18.5404
1   Athlone Industria 1         7764   33.9673    18.5404
2   Athlone Industria 2         7764   33.9673    18.5404
3            Gatesville         7764   33.9673    18.5404
4             Bellville         7530   33.8906    18.6532
5             Bergvliet         7945   34.0708    18.4632
6            Muizenberg         7945   34.0708    18.4632
7               Retreat         7945   34.0708    18.4632
8                 Tokai         7945   34.0708    18.4632
9              Westlake         7945   34.0708    18.4632
10              BO-Kaap         8001   33.9211    18.4217
11              Central         8001   33.9211    18.4217
12         DE Waterkant         8001   33.9211    18.4217
13     Devil'S Peak EST         8001   33.9211    18.4217
14     Duiwelskloof LGD         8001   33.9211    18.4217
15            Foreshore         8001   33.9211    18.4217
16              Gardens         8001   33.9211    18.4217
17            Higgovale         8001   33.9211    18.4217
18            High Cape         8001   33.9211    18.4217
19        Highlands EST         8001   33.9211    18.4217
20        Highlands LGD         8001   33.9211    18.4217
21             Kloofnek         8001   33.9211    18.4217
22          Oranjezicht         8001   33.9211    18.4217
23      Schotsche Kloof         8001   33.9211    18.4217
24           Seinheuwel         8001   33.9211    18.4217
25             Sentraal         8001   33.9211    18.4217
26          Signal Hill         8001   33.9211    18.4217
27    Table BAY Harbour         8001   33.9211    18.4217
28        Tafelbaaihawe         8001   33.9211    18.4217
29        Tamboerskloof         8001   33.9211    18.4217
..                  ...          ...       ...        ...
45           Southfield         7800   34.0107    18.4691
46              Wynberg         7800   34.0107    18.4691
47          Durbanville         7550   33.8475    18.6532
48         Eerste River         7100   33.9970    18.6948
49         Eersterivier         7100   33.9970    18.6948
50            Fish Hoek         7975   34.1418    18.3861
51              Vishoek         7975   34.1418    18.3861
52          Grassy Park         7941   34.0634    18.5107
53        Groote Schuur         7925   33.9353    18.4691
54          Observatory         7925   33.9353    18.4691
55           Salt River         7925   33.9353    18.4691
56       SIR Lowry Road         7925   33.9353    18.4691
57           Soutrivier         7925   33.9353    18.4691
58            Woodstock         7925   33.9353    18.4691
59         Hanover Park         7780   33.9926    18.5166
60            Lansdowne         7780   33.9926    18.5166
61          Khayelitsha         7784   34.0552    18.7007
62             Maitland         7405   33.9209    18.4929
63       Paarden Island         7405   33.9209    18.4929
64        Paardeneiland         7405   33.9209    18.4929
65            Pinelands         7405   33.9209    18.4929
66           Ysterplaat         7405   33.9209    18.4929
67       Matroosfontein         7490   33.9447    18.5819
68      Mitchells Plain         7785   34.0404    18.6235
69      Mitchells Plein         7785   34.0404    18.6235
70          Monte Vista         7460   33.9117    18.5523
71              Mowbray         7700   33.9658    18.4810
72             Newlands         7700   33.9658    18.4810
73             Nuweland         7700   33.9658    18.4810
74                Parow         7500   33.8801    18.5819

[75 rows x 4 columns]